repos:
-   repo: local
    hooks:
    -   id: prettier
        name: prettier
        entry: bunx prettier ./frontend --write
        language: system
        files: \.(css|html|js|jsx|ts|tsx)$
    -   id: biome
        name: biome
        entry: bunx @biomejs/biome check --write
        language: system
        files: \.(css|html|js|jsx|ts|tsx)$
